
export const REQUEST_POPULAR_MOVIE_SAGA = "REQUEST_POPULAR_MOVIE_SAGA"
export const LOAD_POPULAR_MOVIE = "LOAD_POPULAR_MOVIE";
export const POPULAR_MOVIE_REQUEST_SUCCESS = "POPULAR_MOVIE_REQUEST_SUCCESS";
export const POPULAR_MOVIE_REQUEST_FAIL = "POPULAR_MOVIE_REQUEST_FAIL";
