export const REQUEST_UPCOMING_MOVIE = "REQUEST_UPCOMING_MOVIE"

export const LOAD_UPCOMING_MOVIE = "LOAD_UPCOMING_MOVIE"
export const REQUEST_UPCOMING_MOVIE_SUCCESS = "REQUEST_UPCOMING_MOVIE_SUCCESS"
export const REQUEST_UPCOMING_MOVIE_FAILED = "REQUEST_UPCOMING_MOVIE_FAILED"