export const REQUEST_MOVIE_DETAIL_SAGA = "REQUEST_MOVIE_DETAIL";
export const LOAD_DATA = "LOAD_DATA";
export const REQUEST_MOVIE_DETAIL_SUCCESS = "REQUEST_MOVIE_DETAIL_SUCCESS";
export const REQUEST_MOVIE_DETAIL_FAIL = "REQUEST_MOVIE_DETAIL_FAIL";