export const REQUEST_COMMENT = "REQUEST_COMMENT"
export const LOAD_COMMENT = "LOAD_COMMENT"
export const REQUEST_COMMENT_SUCCESS = "REQUEST_COMMENT_SUCCESS"
export const REQUEST_COMMENT_FAILED = "REQUEST_COMMENT_FAILED"

export const SUBMIT_COMMENT_SAGA = "SUBMIT_COMMENT_SAGA";
